### ISSUE TITLE
Crashes on "sync" button press on Arch Linux, KDE

### ISSUE THREAD

**Issue by DJsushi** [rad4day/anki-editor-preview-plugin#17]
Here's what Anki came up with:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (35be9a70) Python 3.11.5 Qt 6.6.0 PyQt 6.5.3
Platform: Linux-6.5.8-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-10-25 16:28:10
Add-ons possibly involved: ⁨Editor Live Preview⁩

Caught exception:
Traceback (most recent call last):
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/webview.py", line 46, in cmd
    return json.dumps(self.onCmd(str))
                      ^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/webview.py", line 153, in _onCmd
    return self._onBridgeCmd(str)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/webview.py", line 666, in _onBridgeCmd
    return self.onBridgeCmd(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/toolbar.py", line 411, in _linkHandler
    self.link_handlers[link]()
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/toolbar.py", line 429, in _browseLinkHandler
    self.mw.onBrowse()
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/main.py", line 1226, in onBrowse
    aqt.dialogs.open("Browser", self, card=self.reviewer.card)
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/__init__.py", line 130, in open
    instance = creator(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/browser/browser.py", line 143, in __init__
    self.setupEditor()
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/browser/browser.py", line 532, in setupEditor
    self.editor = aqt.editor.Editor(
                  ^^^^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/lib/python3.11/site-packages/aqt/editor.py", line 145, in __init__
    gui_hooks.editor_did_init(self)
  File "/home/djsushi/.local/lib/python3.11/site-packages/_aqt/hooks.py", line 2350, in __call__
    hook(editor)
  File "/home/djsushi/.local/share/Anki2/addons21/1960039667/__init__.py", line 47, in editor_init_hook
    self._inject_splitter(ed)
  File "/home/djsushi/.local/share/Anki2/addons21/1960039667/__init__.py", line 89, in _inject_splitter
    split = self._get_splitter(editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djsushi/.local/share/Anki2/addons21/1960039667/__init__.py", line 64, in _get_splitter
    split.setOrientation(Qt.Vertical)
                         ^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'Vertical'
```

If you need more information, please let me know.

**Comment by rad4day** [comment]
This should have been fixed by cefa65e
